### ISSUE TITLE
ContactForm doesn't work

### ISSUE THREAD

**Issue by gouravsood** [chrisotto6/chrisottodev#626]
When trying to submit the contact form, it's never submitting the form. 'handleSubmit' method is not invoked on Submit button click.

**Comment by chrisotto6** [comment]
Thank you for creating a ticket, I will be in touch!' first issue

**Comment by gouravsood** [comment]
Thanks @chrisotto6  for prompt response. Same issue on your website too. https://chrisotto.dev/contact/  is not submitting form.

**Comment by gouravsood** [comment]
@chrisotto6 submitted https://github.com/chrisotto6/chrisottodev/pull/627 Please review. Its working for me locally with the proposed changes.
